apiVersion: apps/v1
kind: Deployment
metadata:
  name: crane-ui-plugin
  namespace: openshift-migration
  labels:
    app: crane-ui-plugin
    app.kubernetes.io/component: crane-ui-plugin
    app.kubernetes.io/instance: crane-ui-plugin
    app.kubernetes.io/part-of: crane-ui-plugin
    app.openshift.io/runtime-namespace: openshift-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crane-ui-plugin
  template:
    metadata:
      labels:
        app: crane-ui-plugin
    spec:
      containers:
        - name: crane-ui-plugin
          image: quay.io/konveyor/crane-ui-plugin
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          args:
            - '--ssl'
            - '--cert=/var/serving-cert/tls.crt'
            - '--key=/var/serving-cert/tls.key'
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: crane-ui-plugin
  namespace: openshift-migration
  labels:
    app: crane-ui-plugin
    app.kubernetes.io/component: crane-ui-plugin
    app.kubernetes.io/instance: crane-ui-plugin
    app.kubernetes.io/part-of: crane-ui-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: crane-ui-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: crane-ui-plugin
spec:
  displayName: 'Konveyor Crane UI Plugin'
  service:
    name: crane-ui-plugin
    namespace: openshift-migration
    port: 9443
    basePath: '/'
  proxy:
    - type: Service
      alias: remote-cluster
      service:
        name: proxy
        namespace: openshift-migration
        port: 80
