name: PR CI Checks
on:
  pull_request:
  push:
    branches:
      - main
      - release*

jobs:
  tests:
    name: Typecheck, Lint, Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Run tsc
        run: yarn tsc
      - name: Run eslint
        run: yarn lint
      - name: Attempt a build
        run: yarn build
